[package]
name = "ipa-macros"
version = "0.1.0"
rust-version = "1.64.0"
edition = "2021"

[features]
compact-gate = []

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.15", features = ["full", "extra-traits"] }
quote = "1.0.27"
