name: Publish Helper Image CI

on:
  workflow_dispatch:
  push:
    paths:
      - "docker/ci/**"
      - ".github/workflows/docker.yml"
      - "Cargo.toml"
  schedule:
    # Once monthly at a randomly selected time.
    - cron: "24 2 3,18 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Setup Docker Buildx"
      uses: docker/setup-buildx-action@v2

    - name: "Login to GitHub Container Registry"
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: "Build and Publish Helper Image"
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/ci/helper.Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/ipa-helper:latest
        platforms: linux/amd64
